#!/usr/bin/env python3
"""Lift the web pages' computation code into the iOS app's engine.

The app runs the site's own JavaScript (sleeper.js, espn.js, demo.js,
insights.js, chat.js) unchanged in a hidden web view, and draws every screen
natively. What the pages compute for themselves (standings as they stood each
week, clinch flags, playoff scenarios, power rankings, the week's recap,
strength of schedule) lives inside each page's own <script>, in a closure
around the page's model. This script copies those passages, verbatim, into
ios/PigskinPantheon/Engine/season-engine.js, wrapped as

    window.SeasonEngine = function (model, season) { ...; return { ... } }

so the app gets exactly the numbers and the words the site shows. Only the
HTML escaping is swapped for plain text (the app draws text, not HTML).

Run it from anywhere after changing season.html:

    python3 ios/tools/sync_engine.py

It fails loudly when a marker it cuts on has moved, rather than producing a
half-copied engine.
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "ios" / "PigskinPantheon" / "Engine" / "season-engine.js"


def between(text: str, start: str, end: str, *, include_end: bool = False) -> str:
    i = text.find(start)
    if i < 0:
        sys.exit(f"sync_engine: start marker not found: {start!r}")
    j = text.find(end, i + len(start))
    if j < 0:
        sys.exit(f"sync_engine: end marker not found after {start!r}: {end!r}")
    return text[i: j + (len(end) if include_end else 0)]


def main() -> None:
    page = (ROOT / "season.html").read_text(encoding="utf-8")

    # The engine, the playoff scenarios and the week in review.
    engine = between(page, "    const SEASON = season.year;", "    /* ---- the Recap view")
    # The recap as plain text, for sharing.
    recap_text = between(page, "    /* ---- the recap as text", "    /* ---- the recap as pictures")
    # Strength of schedule (needs the season before).
    sos = between(page, "    const PRIOR = (() => {", "    function renderSosPanel()")
    # Which views each week offers, and the week the standings read from.
    views = between(page, "    const HAS_BRACKET =", "    /* =================================================================\n       SHARED PIECES")
    # The page's own box-score loader, which the recap reads through.
    box = between(page, "    const boxWeeks = () => model.boxWeeks(SEASON);", "    window.boxWeeks = boxWeeks;")
    weeks_text = between(page, "    const weeksText = ", ";\n", include_end=True)

    # Plain text, not HTML: names are drawn natively.
    engine, n = re.subn(r"const esc = League\.esc;", "const esc = (s) => String(s == null ? \"\" : s);", engine)
    if n != 1:
        sys.exit("sync_engine: couldn't find `const esc = League.esc;` to replace")

    body = "\n".join([engine, recap_text, sos, views, box, weeks_text])

    exports = [
        "SEASON", "REGULAR_WEEKS", "PLAYOFF_TEAMS", "BYES", "MEDIAN", "HAS_PLAYOFFS", "HAS_DIVISIONS",
        "WB_ROUNDS", "LB_ROUNDS", "LAST_WEEK", "DIVISION_NAMES", "divisionOrder", "latestWeek",
        "lastPlayedWeek", "CLINCH_KEY", "TIE_RULE", "PRIOR", "HAS_BRACKET", "SEASON_VIEWS", "HOME_VIEW",
        "state", "computeStats", "buildPicture", "playoffScenarios", "gamesBack", "gamesLeft",
        "gamesOfWeek", "powerRankings", "allPlay", "weekRecap", "recapText", "strengthOfSchedule",
        "viewsFor", "asOfWeek", "isPlayed", "playoffWeekPlayed", "lastPlayoffWeek", "weeksText",
        "boxWeek", "postOf",
    ]
    missing = [name for name in exports if not re.search(rf"\b(const|let|function|async function)\s+{name}\b", body)]
    if missing:
        sys.exit(f"sync_engine: these are no longer defined in the copied passages: {', '.join(missing)}")

    header = f"""/* GENERATED by ios/tools/sync_engine.py from season.html. Don't edit:
   change season.html and run the script again.

   The season page's own computations (records, tiebreaks, clinch flags,
   playoff scenarios, power rankings, the week in review, strength of
   schedule), lifted out of its closure so the app can ask for them. The
   app draws the results natively; nothing here touches the page. */
(function () {{
  "use strict";
  window.SeasonEngine = function (model, season) {{
"""
    footer = f"""
    return {{ {", ".join(exports)} }};
  }};
}})();
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + body + footer, encoding="utf-8")
    print(f"sync_engine: wrote {OUT.relative_to(ROOT)} ({len(body.splitlines())} lines from season.html)")


if __name__ == "__main__":
    main()
