/* GENERATED by ios/tools/sync_engine.py from season.html. Don't edit:
   change season.html and run the script again.

   The season page's own computations (records, tiebreaks, clinch flags,
   playoff scenarios, power rankings, the week in review, strength of
   schedule), lifted out of its closure so the app can ask for them. The
   app draws the results natively; nothing here touches the page. */
(function () {
  "use strict";
  window.SeasonEngine = function (model, season) {
    const SEASON = season.year;
    const S = season.settings;
    const FINISHED = season.finished;
    const REGULAR_WEEKS = S.regularWeeks;
    const PLAYOFF_TEAMS = Math.min(S.playoffTeams, Object.keys(season.teams).length);
    const BYES = S.byes;
    const MEDIAN = S.median;
    const WB = season.winnersBracket;
    const LB = season.losersBracket;
    const HAS_PLAYOFFS = PLAYOFF_TEAMS > 0 && WB.length > 0;
    const WB_ROUNDS = Math.max(0, ...WB.map((g) => g.r));
    const LB_ROUNDS = Math.max(0, ...LB.map((g) => g.r));
    const LAST_WEEK = HAS_PLAYOFFS ? Math.max(REGULAR_WEEKS, S.lastWeek) : REGULAR_WEEKS;

    /* A team's mark for a badge: their Sleeper avatar where there is one,
       otherwise the first character of the team's name. */
    const teamMark = (team) => {
      const src = team && team.ownerId && window.TEAM_LOGOS && window.TEAM_LOGOS[team.ownerId];
      return src ? `<img class="team-logo" src="${src}" alt="">` : League.esc((team && team.icon) || "");
    };

    const teams = season.teams;
    const TEAM_IDS = Object.keys(teams);
    const esc = (s) => String(s == null ? "" : s);
    const nameOf = (id) => esc(teams[id].name);
    const ownerOf = (id) => esc(teams[id].owner);

    /* Divisions as Sleeper has them. A league without divisions is one
       table, headed "Standings". */
    const HAS_DIVISIONS = S.divisions.length > 1;
    const LEAGUE_TABLE = "Standings";
    const divisionOrder = {};
    if (HAS_DIVISIONS) {
      S.divisions.forEach((d) => { divisionOrder[d] = TEAM_IDS.filter((id) => teams[id].division === d); });
      const loose = TEAM_IDS.filter((id) => !teams[id].division);
      if (loose.length) divisionOrder["No Division"] = loose;
      Object.keys(divisionOrder).forEach((d) => { if (!divisionOrder[d].length) delete divisionOrder[d]; });
    } else {
      divisionOrder[LEAGUE_TABLE] = TEAM_IDS.slice();
    }
    const DIVISION_NAMES = Object.keys(divisionOrder);
    const divisionOf = (id) => (HAS_DIVISIONS ? teams[id].division || "No Division" : LEAGUE_TABLE);
    const divisionLabel = (d) => (/division/i.test(d) ? d : `${d} Division`);

    const schedule = season.schedule;
    const results = season.results;
    const medianResults = season.medianResults;
    const playedWeeks = season.playedWeeks;
    const lastPlayedWeek = playedWeeks.length ? playedWeeks[playedWeeks.length - 1] : 0;

    // The postseason games, looked up by bracket and game number.
    const postOf = (bracket, m) => season.postseason.find((g) => g.bracket === bracket && g.m === m) || null;
    const playoffWeekPlayed = (w) => w > REGULAR_WEEKS && w <= season.lastFinal &&
      season.postseason.some((g) => g.played && g.weeks.includes(w));
    const lastPlayoffWeek = () => Math.max(0, ...season.postseason.filter((g) => g.played).map((g) => g.week));
    const latestWeek = Math.max(lastPlayedWeek, lastPlayoffWeek());

    const NUMBER_WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
      "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty"];
    const numberWord = (n) => NUMBER_WORDS[n] || String(n);
    const capital = (s) => s.charAt(0).toUpperCase() + s.slice(1);

    /* =================================================================
       ENGINE — records, tiebreakers, seeding
       ================================================================= */

    /* Primary club colours, with the ink that stays legible on each. */
    const NFL_TEAMS = {
      ARI: "#97233F", ATL: "#A71930", BAL: "#241773", BUF: "#00338D",
      CAR: "#0085CA", CHI: "#0B162A", CIN: "#FB4F14", CLE: "#311D00",
      DAL: "#041E42", DEN: "#FB4F14", DET: "#0076B6", GB:  "#203731",
      HOU: "#03202F", IND: "#002C5F", JAX: "#101820", KC:  "#E31837",
      LAC: "#0080C6", LAR: "#003594", LV:  "#111111", MIA: "#008E97",
      MIN: "#4F2683", NE:  "#002244", NO:  "#A08A5B", NYG: "#0B2265",
      NYJ: "#125740", PHI: "#004C54", PIT: "#FFB612", SEA: "#002244",
      SF:  "#AA0000", TB:  "#D50A0A", TEN: "#0C2340", WSH: "#5A1414",
      FA:  "#8A94A1"
    };

    /* Pittsburgh's yellow needs black text where Philadelphia's green needs
       white, so the ink is derived from the colour rather than assumed. */
    function readableInk(hex) {
      const n = parseInt(hex.slice(1), 16);
      const lum = (0.299 * ((n >> 16) & 255) + 0.587 * ((n >> 8) & 255) + 0.114 * (n & 255)) / 255;
      return lum > 0.62 ? "#0b1726" : "#ffffff";
    }

    const fmt = (n) => Number(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const fmt1 = (n) => Number(n).toFixed(1);
    const pctText = (v) => v.toFixed(3).replace(/^0/, "");

    function gamesThrough(week) {
      const out = [];
      playedWeeks.filter((w) => w <= week).forEach((w) => {
        results[w].forEach(([a, as, b, bs]) => out.push({ week: w, a, as, b, bs }));
      });
      return out;
    }

    function blankLine(id) {
      return {
        id,
        wins: 0, losses: 0, ties: 0, gp: 0,
        pf: 0, pa: 0,
        divWins: 0, divLosses: 0, divTies: 0,
        form: []
      };
    }

    // Records for every team through the given week. In a league that also
    // plays the week's median, that result counts as a game too, as it does
    // in Sleeper's standings.
    function computeStats(week) {
      const stats = {};
      TEAM_IDS.forEach((id) => { stats[id] = blankLine(id); });

      gamesThrough(week).forEach((g) => {
        const sameDivision = HAS_DIVISIONS && divisionOf(g.a) === divisionOf(g.b);
        [[g.a, g.as, g.b, g.bs], [g.b, g.bs, g.a, g.as]].forEach(([id, own, oppId, opp]) => {
          const line = stats[id];
          line.gp += 1;
          line.pf += own;
          line.pa += opp;
          if (own > opp) { line.wins += 1; if (sameDivision) line.divWins += 1; line.form.push("W"); }
          else if (own < opp) { line.losses += 1; if (sameDivision) line.divLosses += 1; line.form.push("L"); }
          else { line.ties += 1; if (sameDivision) line.divTies += 1; line.form.push("T"); }
        });
      });

      if (MEDIAN) {
        playedWeeks.filter((w) => w <= week).forEach((w) => {
          Object.entries(medianResults[w] || {}).forEach(([id, r]) => {
            const line = stats[id];
            if (!line) return;
            if (r === "W") line.wins += 1; else if (r === "L") line.losses += 1; else line.ties += 1;
          });
        });
      }

      TEAM_IDS.forEach((id) => {
        const t = stats[id];
        const decided = t.wins + t.losses + t.ties;
        t.pct = decided ? (t.wins + t.ties * 0.5) / decided : 0;
        t.score = t.wins + t.ties * 0.5;
        t.divGp = t.divWins + t.divLosses + t.divTies;
        t.divPct = t.divGp ? (t.divWins + t.divTies * 0.5) / t.divGp : 0;
        t.record = t.ties ? `${t.wins}–${t.losses}–${t.ties}` : `${t.wins}–${t.losses}`;
        t.divRecord = t.divTies ? `${t.divWins}–${t.divLosses}–${t.divTies}` : `${t.divWins}–${t.divLosses}`;
        t.pf = Math.round(t.pf * 100) / 100;
        t.pa = Math.round(t.pa * 100) / 100;
        t.pfg = t.gp ? t.pf / t.gp : 0;
        t.pag = t.gp ? t.pa / t.gp : 0;
        t.diff = t.pf - t.pa;
        t.diffPerGame = t.gp ? t.diff / t.gp : 0;
      });

      return stats;
    }

    // A team can be caught in several races at once — its division, the
    // playoff seeding — so reasons accumulate.
    function addReason(reasons, id, entry) {
      if (!reasons) return;
      (reasons[id] = reasons[id] || []).push(entry);
    }

    /* Sleeper's order: record, then points for. Teams level on both are
       left as Sleeper would leave them, in roster order, and flagged. */
    function rankIds(ids, stats) {
      return ids.slice().sort((a, b) =>
        (stats[b].score - stats[a].score) || (stats[b].pf - stats[a].pf) || (teams[a].rosterId - teams[b].rosterId));
    }

    /* Any run of teams level on record inside an ordered race was separated
       on points for, so each of them gets an explanation. */
    // Who settles a tie on points for: Sleeper does; ESPN's own tiebreaks
    // vary by league, so for ESPN the site says it is its own order.
    const TIE_RULE = League.sourceName() === "Sleeper" ? "Sleeper" : "This site";
    function explainTies(ordered, stats, reasons, flips, race) {
      let i = 0;
      while (i < ordered.length) {
        let j = i;
        while (j + 1 < ordered.length && stats[ordered[j + 1]].score === stats[ordered[i]].score) j += 1;
        if (j > i) {
          const group = ordered.slice(i, j + 1);
          const ladder = group.map((id) => `${nameOf(id)} ${fmt(stats[id].pf)}`).join(", ");
          for (let k = 1; k < group.length; k++) {
            if (stats[group[k - 1]].pf === stats[group[k]].pf) flips.push([group[k - 1], group[k]]);
          }
          const detail = group.length === 2
            ? `${nameOf(group[0])} and ${nameOf(group[1])} were both ${stats[group[0]].record}. ${TIE_RULE} breaks the tie on points for: ${ladder}.`
            : `${group.length} teams sat at ${stats[group[0]].record}. ${TIE_RULE} ranks them on points for: ${ladder}.`;
          group.forEach((id, k) => {
            addReason(reasons, id, { race, criterion: "Points for", detail, over: group[k + 1] || null, under: k ? group[k - 1] : null });
          });
        }
        i = j + 1;
      }
    }

    // Division standings: record first, ties on points for.
    function orderDivision(division, week, stats, flips, reasons) {
      const ordered = rankIds(divisionOrder[division], stats);
      explainTies(ordered, stats, reasons, flips, HAS_DIVISIONS ? "Division standings" : "Standings");
      return ordered;
    }

    /* Games back of a leader, the standard baseball formula. */
    function gamesBack(leader, team) {
      return ((leader.wins - team.wins) + (team.losses - leader.losses)) / 2;
    }

    // The regular-season weeks still to come in which a team has a game.
    function gamesLeft(id, week) {
      let n = 0;
      for (let w = week + 1; w <= REGULAR_WEEKS; w++) {
        if ((schedule[w] || []).some(([a, b]) => a === id || b === id)) n += 1;
      }
      return n;
    }

    /* Clinch and elimination flags. Every test here is a *sufficient*
       condition, so a badge is never shown unless it is mathematically
       settled; a team can be safe before the badge appears, never after.
       Anyone who could still finish level on record is counted as a threat,
       since points for, the tiebreaker, cannot be known in advance.

       With divisions, every division's leader is seeded ahead of the rest,
       so a team that has not locked up its own division must also leave
       room for a leader of every division to be seeded above it. */
    function clinchFlags(week, stats, seeds, leaders) {
      const flags = {};
      if (!HAS_PLAYOFFS) return flags;
      const P = PLAYOFF_TEAMS;
      const seasonOver = week >= REGULAR_WEEKS || TEAM_IDS.every((id) => !gamesLeft(id, week));
      if (seasonOver) {
        seeds.forEach((id, i) => {
          flags[id] = (BYES ? i < BYES : HAS_DIVISIONS && leaders.includes(id)) ? "z" : i < P ? "x" : "e";
        });
        return flags;
      }

      const unit = MEDIAN ? 2 : 1;
      return flagsFromBounds(
        (id) => stats[id].score,
        (id) => stats[id].score + gamesLeft(id, week) * unit
      );
    }

    /* The flags themselves, from the fewest and most wins each team can
       still finish with. Shared with the playoff scenarios below, which ask
       the same question of every way next week could go. */
    function flagsFromBounds(minW, maxW) {
      const flags = {};
      const P = PLAYOFF_TEAMS;
      const D = HAS_DIVISIONS ? DIVISION_NAMES.length : 0;

      TEAM_IDS.forEach((id) => {
        const others = TEAM_IDS.filter((x) => x !== id);
        const couldCatch = others.filter((x) => maxW(x) >= minW(id)).length;
        const sureAhead = others.filter((x) => minW(x) > maxW(id)).length;
        const rivals = HAS_DIVISIONS ? others.filter((x) => divisionOf(x) === divisionOf(id)) : [];
        const ownDivision = HAS_DIVISIONS && rivals.every((x) => maxW(x) < minW(id));
        const lostDivision = !HAS_DIVISIONS || rivals.some((x) => minW(x) > maxW(id));

        let bye = false;
        if (BYES) {
          if (!HAS_DIVISIONS) bye = couldCatch < BYES;
          else if (ownDivision) {
            // Other divisions that could still produce a leader seeded above it.
            const threats = DIVISION_NAMES.filter((d) => d !== divisionOf(id) &&
              divisionOrder[d].some((x) => maxW(x) >= minW(id))).length;
            bye = threats < BYES;
          }
        }
        const berth = ownDivision || couldCatch + (HAS_DIVISIONS ? D - 1 : 0) < P;
        const out = lostDivision && sureAhead >= P;
        flags[id] = bye || (!BYES && ownDivision) ? "z" : berth ? "x" : out ? "e" : null;
      });
      return flags;
    }

    const CLINCH_KEY = {
      z: { label: "z", title: BYES ? "Clinched a first-round bye" : "Clinched the division" },
      x: { label: "x", title: "Clinched a playoff berth" },
      e: { label: "e", title: "Eliminated from playoff contention" }
    };

    /* The whole playoff picture as it stands after the given week. */
    const pictureCache = {};
    function buildPicture(week) {
      if (pictureCache[week]) return pictureCache[week];
      const stats = computeStats(week);
      const flips = [];
      const reasons = {};
      const divisions = {};
      DIVISION_NAMES.forEach((d) => { divisions[d] = orderDivision(d, week, stats, flips, reasons); });

      let seeds, leaders = [];
      if (HAS_DIVISIONS) {
        leaders = rankIds(DIVISION_NAMES.filter((d) => d !== "No Division").map((d) => divisions[d][0]).filter(Boolean), stats);
        const rest = rankIds(TEAM_IDS.filter((id) => !leaders.includes(id)), stats);
        explainTies(rest, stats, reasons, flips, "Playoff seeding");
        seeds = [...leaders, ...rest];
      } else {
        seeds = divisions[LEAGUE_TABLE].slice();
      }

      const seedLabels = {};
      if (HAS_PLAYOFFS) {
        seeds.forEach((id, i) => {
          const chip = `#${i + 1}`;
          if (i < BYES) seedLabels[id] = { chip, kind: "div", lead: true, note: `${chip} seed · first-round bye` };
          else if (i < PLAYOFF_TEAMS && leaders.includes(id)) seedLabels[id] = { chip, kind: "div", note: `${divisionOf(id)} leader` };
          else if (i < PLAYOFF_TEAMS) seedLabels[id] = { chip, kind: HAS_DIVISIONS ? "wc" : "div", note: HAS_DIVISIONS ? "Wild card" : `${chip} seed` };
          else seedLabels[id] = { chip, kind: "out", note: LB.length ? "Losers bracket" : "Missed the playoffs" };
        });
      }

      const flipPairs = flips.filter(([a, b], i, arr) =>
        arr.findIndex(([x, y]) => (x === a && y === b) || (x === b && y === a)) === i);

      const result = {
        week, stats, divisions, seeds, leaders, seedLabels, flips: flipPairs, reasons,
        playoffField: seeds.slice(0, PLAYOFF_TEAMS),
        firstOut: seeds[PLAYOFF_TEAMS] || null
      };
      result.flags = clinchFlags(week, stats, seeds, leaders);
      pictureCache[week] = result;
      return result;
    }

    /* =================================================================
       WHAT'S AT STAKE: next week's playoff scenarios, in words.

       Every way next week's games could go is played out, and each team is
       asked the same question the clinch badges ask (flagsFromBounds): is it
       settled? A team's scenarios are then boiled down to the fewest results
       that settle it: "clinches with a win", "clinches with a loss if the
       Dawgs beat MCM22". The median game can't be known in advance, so it is
       left open, and so is points for: every scenario here settles things
       outright, whatever the scores.
       ================================================================= */

    const scenarioCache = {};
    function playoffScenarios(week) {
      if (week in scenarioCache) return scenarioCache[week];
      const W = week + 1;
      const games = (schedule[W] || []).slice();
      let out = null;
      if (HAS_PLAYOFFS && !FINISHED && W <= REGULAR_WEEKS && games.length && games.length <= 12) {
        const stats = computeStats(week);
        const now = buildPicture(week).flags;
        const unit = MEDIAN ? 2 : 1;
        const left = Object.fromEntries(TEAM_IDS.map((id) => [id, gamesLeft(id, W)]));
        // outcome bit i set: the first team of game i wins
        const outcomes = [];
        for (let mask = 0; mask < (1 << games.length); mask++) {
          const won = new Set(games.map(([a, b], i) => ((mask >> i) & 1 ? a : b)));
          const minW = (id) => stats[id].score + (won.has(id) ? 1 : 0);
          const maxW = (id) => minW(id) + (MEDIAN ? 1 : 0) + left[id] * unit;
          outcomes.push(flagsFromBounds(minW, maxW));
        }
        const literal = (i, bit) => ({ i, bit, winner: bit ? games[i][0] : games[i][1], loser: bit ? games[i][1] : games[i][0] });
        const holds = (mask, lits) => lits.every((l) => ((mask >> l.i) & 1) === l.bit);
        const says = (lit) => `${nameOf(lit.winner)} beat${/s$/i.test(teams[lit.winner].name) ? "" : "s"} ${nameOf(lit.loser)}`;

        /* The simplest conditions under which `good` is certain, given the
           team's own result: nothing more, or one other result (any of
           several), or two together. */
        function conditions(masks, good, skip) {
          if (!masks.length) return null;
          if (masks.every((m) => good(outcomes[m]))) return [];
          const lits = [];
          games.forEach((_, i) => { if (i !== skip) lits.push(literal(i, 1), literal(i, 0)); });
          const works = (set) => { const hit = masks.filter((m) => holds(m, set)); return hit.length && hit.every((m) => good(outcomes[m])); };
          const singles = lits.filter((l) => works([l])).map((l) => [l]);
          if (singles.length) return singles;
          const pairs = [];
          for (let a = 0; a < lits.length && pairs.length < 3; a++) {
            for (let b = a + 1; b < lits.length && pairs.length < 3; b++) {
              if (lits[a].i !== lits[b].i && works([lits[a], lits[b]])) pairs.push([lits[a], lits[b]]);
            }
          }
          return pairs.length ? pairs : null;
        }
        const phrase = (conds) => conds.map((set) => set.map(says).join(" and ")).join(", or ");

        const rows = [];
        TEAM_IDS.forEach((id) => {
          const gi = games.findIndex(([a, b]) => a === id || b === id);
          const all = outcomes.map((_, m) => m);
          const wins = (m) => (((m >> gi) & 1) === 1) === (games[gi][0] === id);
          const winMasks = gi < 0 ? [] : all.filter(wins);
          const lossMasks = gi < 0 ? [] : all.filter((m) => !wins(m));
          const lines = [];
          // What settles a goal, without the goal's name: "with a win", ...
          const goal = (good, already) => {
            if (already) return null;
            if (gi < 0) {
              const c = conditions(all, good, -1);
              return c ? (c.length ? `if ${phrase(c)}` : "this week, whatever happens") : null;
            }
            const w = conditions(winMasks, good, gi);
            const l = conditions(lossMasks, good, gi);
            if (w && l && !w.length && !l.length) return "this week, win or lose";
            const parts = [];
            if (w) parts.push(w.length ? `with a win if ${phrase(w)}` : "with a win");
            if (l) parts.push(l.length ? `with a loss if ${phrase(l)}` : "even with a loss");
            return parts.length ? parts.join(", or ") : null;
          };
          const flag = now[id];
          const top = BYES || HAS_DIVISIONS ? goal((f) => f[id] === "z", flag === "z") : null;
          const berth = goal((f) => f[id] === "x" || f[id] === "z", flag === "x" || flag === "z");
          if (top) lines.push(`${BYES ? "Clinches a first-round bye" : "Clinches the division"} ${top}`);
          // A bye comes with a playoff spot: said once when it's the same result.
          if (berth && berth !== top) lines.push(`Clinches a playoff spot ${berth}`);
          // Elimination is about the team's own loss; a win never eliminates.
          if (!flag && gi >= 0) {
            const c = conditions(lossMasks, (f) => f[id] === "e", gi);
            if (c) lines.push(c.length ? `Eliminated with a loss if ${phrase(c)}` : "Eliminated with a loss");
          } else if (!flag && gi < 0) {
            const c = conditions(all, (f) => f[id] === "e", -1);
            if (c) lines.push(c.length ? `Eliminated if ${phrase(c)}` : "Eliminated this week");
          }
          if (lines.length) rows.push({ id, lines });
        });
        const seedOf = (id) => buildPicture(week).seeds.indexOf(id);
        rows.sort((a, b) => seedOf(a.id) - seedOf(b.id));
        out = { week: W, rows };
      }
      scenarioCache[week] = out;
      return out;
    }

    function scenarioCard(week) {
      const sc = playoffScenarios(week);
      if (!sc || !sc.rows.length) return "";
      return `<article class="card scenario-card">
        ${cardHead(`What's at stake · Week ${sc.week}`, "shield", "Playoff scenarios")}
        <div class="scenario-list">${sc.rows.map((r) => `
          <div class="scenario-row">
            <span class="scenario-team">${miniTeam(r.id)}<strong>${nameOf(r.id)}</strong></span>
            <ul>${r.lines.map((l) => `<li>${l}.</li>`).join("")}</ul>
          </div>`).join("")}
        </div>
        <p class="scenario-note">Only results that settle it outright are listed. A tie on record goes to points for${MEDIAN ? ", and the median game is still to be played," : ","} which can't be known in advance, so a team can also get in on points.</p>
      </article>`;
    }

    /* =================================================================
       THE WEEK'S BENCH BLUNDER, and the recap to share it in.
       ================================================================= */

    const playerName = (db, pid) => esc(db[pid] ? db[pid][0] : `Player ${pid}`);

    // The costliest benching of the week, into its tile in the week's notes.
    function fillBlunder(week) {
      const tile = document.querySelector(`[data-blunder-week="${week}"]`);
      if (!tile || !window.Insights) return;
      Promise.all([Insights.lineupWeek(model, SEASON, week), League.players()]).then(([lw, db]) => {
        if (!tile.isConnected) return;
        const worst = lw && lw.rows.filter((r) => r.blunder && r.blunder.cost > 0).sort((a, b) => b.blunder.cost - a.blunder.cost)[0];
        if (!worst) { tile.querySelector("strong").textContent = "Every lineup was perfect"; tile.querySelector("span").textContent = ""; return; }
        const b = worst.blunder;
        tile.querySelector("strong").innerHTML = `${nameOf(worst.teamId)} benched ${playerName(db, b.benched.pid)}`;
        tile.querySelector("span").innerHTML = `${fmt(b.benched.pts)} on the bench${b.started ? `, started ${playerName(db, b.started.pid)} (${fmt(b.started.pts)})` : ""}${worst.costGame ? " · cost the game" : ""}`;
      }).catch(() => { tile.remove(); });
    }

    /* =================================================================
       THE WEEK IN REVIEW

       weekRecap(week) reads everything the league did in a week and writes
       it up: a headline, every game with its story (an upset, a streak
       snapped, a score for the record books, the bench that would have
       won it), power rankings, the luck report, the players of the week,
       the front office's moves, the playoff race and next week's games.
       The Recap view draws it as a page; the share sheet as two pictures
       for a group chat and as plain text.

       Nothing here is a projection: every story is told from what Sleeper
       has already scored. "League history" means every season this league
       has played up to and including the week, so an old week reads as it
       would have that Monday.
       ================================================================= */

    const plain = (id) => teams[id].name;
    const ordinal = (n) => { const s = ["th", "st", "nd", "rd"], v = n % 100; return `${n}${s[(v - 20) % 10] || s[v] || s[0]}`; };
    const ordWord = (n) => (n === 1 ? "" : `${ordinal(n)}-`);
    const recordText = (w, l, t) => (t ? `${w}–${l}–${t}` : `${w}–${l}`);
    const plural = (n, one, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;
    const verbS = (name, verb) => (/s$/i.test(name) ? verb : `${verb}s`);   // "the Dawgs beat", "MCM22 beats"

    // A week's played games: the regular season's, or the playoffs' (a
    // two-week round counts in the week it ends).
    function gamesOfWeek(w) {
      if (w <= REGULAR_WEEKS) return (results[w] || []).map(([a, as, b, bs]) => ({ a, as, b, bs, label: "", final: false }));
      return season.postseason
        .filter((g) => g.played && g.week === w && g.a && g.b)
        .sort((x, y) => (x.bracket === y.bracket ? (x.p || 99) - (y.p || 99) : x.bracket === "W" ? -1 : 1))
        .map((g) => ({
          a: g.a, as: g.aScore, b: g.b, bs: g.bScore, label: g.label, multi: g.weeks.length > 1,
          final: g.bracket === "W" && g.titlePath && g.r === WB_ROUNDS,
          consolation: g.bracket === "L",
        }));
    }

    /* Every game this league has played, all seasons, as owners (so a
       manager's history follows them from team name to team name). */
    let historyGames = null;
    function leagueGames() {
      if (historyGames) return historyGames;
      historyGames = [];
      model.seasons.forEach((s) => {
        Object.keys(s.results).map(Number).forEach((w) => (s.results[w] || []).forEach(([a, as, b, bs]) => {
          if (!s.teams[a] || !s.teams[b]) return;
          historyGames.push({ year: s.year, week: w, oa: s.teams[a].ownerId, ob: s.teams[b].ownerId, as, bs, playoff: false, multi: false });
        }));
        s.postseason.filter((g) => g.played && g.a && g.b && s.teams[g.a] && s.teams[g.b]).forEach((g) => {
          historyGames.push({ year: s.year, week: g.week, oa: s.teams[g.a].ownerId, ob: s.teams[g.b].ownerId, as: g.aScore, bs: g.bScore, playoff: true, multi: g.weeks.length > 1 });
        });
      });
      return historyGames;
    }

    /* All-play: every team against every other team's score, week by week,
       across the regular-season weeks from..through. */
    function allPlay(through, from = 1) {
      const out = Object.fromEntries(TEAM_IDS.map((id) => [id, { w: 0, n: 0 }]));
      playedWeeks.filter((w) => w >= from && w <= through).forEach((w) => {
        const sc = [];
        (results[w] || []).forEach(([a, as, b, bs]) => { sc.push([a, as]); sc.push([b, bs]); });
        sc.forEach(([id, p]) => sc.forEach(([o, q]) => {
          if (o === id) return;
          out[id].n++;
          out[id].w += p > q ? 1 : p === q ? 0.5 : 0;
        }));
      });
      return out;
    }

    /* Power rankings through a week: all-play win rate (how a team would
       fare against everyone, every week) counts most, then the actual
       record, the last three weeks' all-play, and points per game. */
    const powerCache = {};
    function powerRankings(through) {
      if (through < 1) return null;
      if (powerCache[through]) return powerCache[through];
      const st = computeStats(through);
      const ap = allPlay(through);
      const recent = allPlay(through, Math.max(1, through - 2));
      const live = TEAM_IDS.filter((id) => st[id].gp);
      const pfgs = live.map((id) => st[id].pfg);
      const lo = Math.min(...pfgs), hi = Math.max(...pfgs);
      const rows = live.map((id) => {
        const apPct = ap[id].n ? ap[id].w / ap[id].n : 0;
        const rcPct = recent[id].n ? recent[id].w / recent[id].n : apPct;
        const pts = hi > lo ? (st[id].pfg - lo) / (hi - lo) : 0.5;
        const h2h = st[id].form.reduce((n, r) => n + (r === "W" ? 1 : r === "T" ? 0.5 : 0), 0);
        const expected = apPct * st[id].form.length;
        return {
          id, score: 100 * (0.4 * apPct + 0.25 * st[id].pct + 0.2 * rcPct + 0.15 * pts),
          record: st[id].record, pf: st[id].pf, pfg: st[id].pfg, apPct, rcPct,
          apRecord: recordText(Math.round(ap[id].w), Math.round(ap[id].n - ap[id].w)),
          luck: h2h - expected,
        };
      }).sort((a, b) => b.score - a.score);
      rows.forEach((r, i) => { r.rank = i + 1; });
      powerCache[through] = rows;
      return rows;
    }

    const streakOf = (form) => {
      if (!form.length) return { kind: null, n: 0 };
      const kind = form[form.length - 1];
      let n = 0;
      for (let i = form.length - 1; i >= 0 && form[i] === kind; i--) n++;
      return { kind, n };
    };

    const recapCache = {};
    function weekRecap(week) {
      if (!recapCache[week]) recapCache[week] = buildRecap(week).catch((err) => { delete recapCache[week]; throw err; });
      return recapCache[week];
    }

    async function buildRecap(week) {
      const playoff = week > REGULAR_WEEKS;
      const games = gamesOfWeek(week);
      const [lw, db, txns, box, wire] = await Promise.all([
        window.Insights ? Insights.lineupWeek(model, SEASON, week).catch(() => null) : null,
        League.players(),
        model.transactions().catch(() => ({})),
        boxWeek(week),
        window.Insights && !playoff ? Insights.waivers(model, SEASON).catch(() => null) : null,
      ]);
      const pname = (pid) => (db[pid] ? db[pid][0] : `Player ${pid}`);
      const oid = (id) => teams[id].ownerId;

      /* ---- the week's scores ---------------------------------------- */
      const scores = [];
      games.forEach((g) => {
        scores.push({ id: g.a, pts: g.as, opp: g.b, oppPts: g.bs, game: g });
        scores.push({ id: g.b, pts: g.bs, opp: g.a, oppPts: g.as, game: g });
      });
      const single = scores.filter((s) => !s.game.multi);
      single.forEach((s) => {
        s.ap = single.reduce((n, o) => n + (o === s ? 0 : o.pts < s.pts ? 1 : o.pts === s.pts ? 0.5 : 0), 0);
        s.apOf = single.length - 1;
        s.rank = 1 + single.filter((o) => o.pts > s.pts).length;
      });
      const byPts = single.slice().sort((x, y) => y.pts - x.pts);
      const total = single.reduce((n, s) => n + s.pts, 0);
      const avg = single.length ? total / single.length : 0;
      const sorted = single.map((s) => s.pts).sort((x, y) => x - y);
      const median = sorted.length ? (sorted.length % 2 ? sorted[(sorted.length - 1) / 2] : (sorted[sorted.length / 2 - 1] + sorted[sorted.length / 2]) / 2) : 0;

      /* ---- league history, as it stood that week ---------------------- */
      const H = leagueGames();
      const upTo = (g) => g.year < SEASON || (g.year === SEASON && g.week <= week);
      const before = (g) => g.year < SEASON || (g.year === SEASON && g.week < week);
      const histScores = [], seasonScores = [], histMargins = [];
      H.forEach((g) => {
        if (g.multi || !upTo(g)) return;
        histScores.push(g.as, g.bs);
        histMargins.push(Math.abs(g.as - g.bs));
        if (g.year === SEASON) seasonScores.push(g.as, g.bs);
      });
      const yearsOfHistory = new Set(H.filter(upTo).map((g) => g.year)).size;
      const highRank = (p) => 1 + histScores.filter((x) => x > p).length;
      const lowRank = (p) => 1 + histScores.filter((x) => x < p).length;
      const marginRank = (m) => 1 + histMargins.filter((x) => x > m).length;
      const seasonHigh = (p) => week > 1 && seasonScores.every((x) => x <= p);
      function series(oa, ob) {
        const s = { a: 0, b: 0, t: 0, lastA: null, lastB: null };
        H.forEach((g) => {
          if (!before(g)) return;
          const m = g.oa === oa && g.ob === ob ? [g.as, g.bs] : g.oa === ob && g.ob === oa ? [g.bs, g.as] : null;
          if (!m) return;
          if (m[0] > m[1]) { s.a++; s.lastA = g.year; } else if (m[0] < m[1]) { s.b++; s.lastB = g.year; } else s.t++;
        });
        s.n = s.a + s.b + s.t;
        return s;
      }
      const careerWins = (owner, pred) => H.reduce((n, g) => n + (pred(g) && ((g.oa === owner && g.as > g.bs) || (g.ob === owner && g.bs > g.as)) ? 1 : 0), 0);

      /* ---- records and form, before and after the week --------------- */
      const statsBefore = !playoff ? computeStats(Math.max(0, week - 1)) : null;
      const statsAfter = computeStats(Math.min(week, REGULAR_WEEKS));
      const lineupOf = (id) => (lw && lw.byTeam[id]) || null;

      /* ---- the players ----------------------------------------------- */
      const lineups = {};
      ((box && box.games) || []).forEach((g) => Object.entries(g.lineups).forEach(([id, list]) => { lineups[id] = list; }));
      const starters = [], bench = [];
      Object.entries(lineups).forEach(([id, list]) => list.forEach((p) => (p.starter ? starters : bench).push({ ...p, teamId: id })));
      starters.sort((a, b) => b.pts - a.pts);
      bench.sort((a, b) => b.pts - a.pts);
      const topOf = (id) => (lineups[id] || []).filter((p) => p.starter).sort((a, b) => b.pts - a.pts)[0] || null;
      const POS = ["QB", "RB", "WR", "TE", "K", "DEF"];
      const byPos = POS.map((pos) => starters.find((p) => p.pos === pos)).filter(Boolean);
      const duds = starters.filter((p) => ["QB", "RB", "WR", "TE"].includes(p.pos)).sort((a, b) => a.pts - b.pts);

      /* ---- every game, with its story ---------------------------------- */
      const notesFor = [];
      const gameStories = games.map((g) => {
        const tie = g.as === g.bs;
        const [w, ws, l, ls] = g.as >= g.bs ? [g.a, g.as, g.b, g.bs] : [g.b, g.bs, g.a, g.as];
        const m = ws - ls;
        const W = plain(w), L = plain(l);
        const notes = [];   // { pri, note, head: a headline it could carry, kind }
        const add = (pri, note, head, kind = "") => notes.push({ pri, note, head, kind });
        const verb = tie ? "tied" : m < 2 ? "edged" : m < 12 ? "beat" : m < 35 ? "handled" : "crushed";
        const line = tie ? `${W} and ${L} tied at ${fmt(ws)}` : `${W} ${verb} ${L}, ${fmt(ws)}–${fmt(ls)}`;
        if (g.final && !tie) add(100, `${W} are champions`, { title: `${W} are champions`, dek: `${W} beat ${L} ${fmt(ws)}–${fmt(ls)} in the final.` }, "title");
        if (!g.multi && !tie) {
          const hr = highRank(ws);
          if (hr === 1 && yearsOfHistory > 1) add(95, `The highest score in league history`, { title: `${W} hang ${fmt(ws)} on ${L}`, dek: `The highest score in the league's ${plural(yearsOfHistory, "season")}.` }, "high");
          else if (hr <= 5 && yearsOfHistory > 1) add(78, `The ${ordinal(hr)}-highest score in league history`, { title: `${W} put up ${fmt(ws)}`, dek: `The ${ordinal(hr)}-highest score in league history, in a win over ${L}.` }, "high");
          else if (seasonHigh(ws)) add(55, `A season-high score`, { title: `${W} drop a season-high ${fmt(ws)}`, dek: `${L} were the ones in the way, ${fmt(ws)}–${fmt(ls)}.` }, "high");
          const lr = lowRank(ls);
          if (lr <= 3 && yearsOfHistory > 1) add(70, `${L}'s ${fmt(ls)} is the ${ordWord(lr)}lowest score in league history`, { title: `${L} manage just ${fmt(ls)}`, dek: `The ${ordWord(lr)}lowest score in league history.` }, "low");
          const mr = marginRank(m);
          if (mr <= 3 && yearsOfHistory > 1) add(76, `The ${ordWord(mr)}biggest blowout in league history`, { title: `${W} crush ${L} by ${fmt(m)}`, dek: `The ${ordWord(mr)}biggest margin the league has seen.` }, "margin");
          else if (m >= 50) add(30, "", { title: `${W} rout ${L}`, dek: `A ${fmt(m)}-point win, ${fmt(ws)}–${fmt(ls)}.` }, "margin");
          if (m < 2) add(64, "", { title: `${W} survive ${L} by ${fmt(m)}`, dek: `${fmt(ws)}–${fmt(ls)}, the week's closest finish.` }, "close");
        }
        if (statsBefore && !tie) {
          const bw = statsBefore[w], bl = statsBefore[l];
          if (bw.gp >= 3 && bl.gp >= 3 && bl.pct - bw.pct >= 0.25) {
            add(74 + Math.round(40 * (bl.pct - bw.pct)), `An upset: ${bw.record} over ${bl.record}`, { title: `${W} stun ${L}`, dek: `${W} (${bw.record}) took down ${L} (${bl.record}), ${fmt(ws)}–${fmt(ls)}.` }, "upset");
          }
          const sl = streakOf(bl.form), sw = streakOf(bw.form);
          if (sl.kind === "W" && sl.n >= 3) add(66 + sl.n, `Snapped ${L}'s ${sl.n}-game winning streak`, { title: `${W} end ${L}'s ${sl.n}-game run`, dek: `${fmt(ws)}–${fmt(ls)}.` }, "streak");
          if (sw.kind === "L" && sw.n >= 3) add(56 + sw.n, `Ended a ${sw.n}-game losing streak`, { title: `${W} snap a ${sw.n}-game skid`, dek: `${verbS(W, "beat")} ${L}, ${fmt(ws)}–${fmt(ls)}.` }, "streak");
          const aw = streakOf(statsAfter[w].form), al = streakOf(statsAfter[l].form);
          if (aw.kind === "W" && aw.n >= 4) add(40 + aw.n, `${aw.n} wins in a row for ${W}`, aw.n >= 6 ? { title: `${W} make it ${aw.n} straight`, dek: `${verbS(W, "beat")} ${L}, ${fmt(ws)}–${fmt(ls)}.` } : null, "streak");
          if (al.kind === "L" && al.n >= 4) add(36 + al.n, `${al.n} losses in a row for ${L}`, null, "streak");
        }
        // The rivalry, owner against owner, every season.
        if (!tie) {
          const sr = series(oid(w), oid(l));
          if (!sr.n && yearsOfHistory > 1) add(20, `Their first ever meeting`);
          else if (!sr.a && sr.n >= 3) add(68, `${W}'s first win over ${L} in ${sr.n + 1} tries`, { title: `${W} finally beat ${L}`, dek: `A first win in ${sr.n + 1} meetings, ${fmt(ws)}–${fmt(ls)}.` }, "series");
          else if (sr.lastA && sr.lastA < SEASON - 1) add(52, `${W}'s first win over ${L} since ${sr.lastA}`);
          else if (sr.n >= 2) {
            const a = sr.a + 1, b = sr.b;
            add(22, a > b ? `${W} lead the all-time series ${recordText(a, b, sr.t)}` : a === b ? `The all-time series is tied ${recordText(a, b, sr.t)}` : `${L} still lead the all-time series ${recordText(b, a, sr.t)}`);
          }
          const now = careerWins(oid(w), before) + 1;
          if (now % 25 === 0) add(60, `${teams[w].owner}'s ${ordinal(now)} career win`, { title: `${teams[w].owner} reaches ${now} wins`, dek: `${verbS(W, "beat")} ${L} for career win number ${now}.` }, "milestone");
        }
        // Luck, and the bench.
        const sw2 = single.find((s) => s.id === w), sl2 = single.find((s) => s.id === l);
        if (!tie && sw2 && sw2.apOf >= 5 && sw2.ap / sw2.apOf < 0.35) add(50, `${W} won with only the week's ${ordinal(sw2.rank)}-best score`);
        if (!tie && sl2 && sl2.apOf >= 5 && sl2.ap / sl2.apOf > 0.65) add(53, `${L} lost with the week's ${ordWord(sl2.rank)}highest score`);
        const lu = lineupOf(l);
        if (!tie && lu && lu.costGame) add(62, `${L}'s best lineup would have scored ${fmt(lu.optimal)} and won`, { title: `${L}'s bench costs them`, dek: `Their best lineup would have scored ${fmt(lu.optimal)} to ${W}'s ${fmt(ws)}.`, weight: lu.optimal - ws }, "bench");
        notes.sort((a, b) => b.pri - a.pri);
        notes.forEach((n) => { if (n.head) notesFor.push({ ...n.head, pri: n.pri + (n.kind === "margin" ? m / 100 : 0) + (n.head.weight || 0) / 100, kind: n.kind }); });
        return {
          a: g.a, as: g.as, b: g.b, bs: g.bs, w, l, ws, ls, tie, label: g.label, final: g.final, consolation: g.consolation,
          line, notes: notes.filter((n) => n.note).slice(0, 2).map((n) => n.note),
          stars: [topOf(g.a), topOf(g.b)],
        };
      });

      /* ---- power rankings and luck ------------------------------------ */
      const power = !playoff ? powerRankings(week) : null;
      const prev = !playoff && week > 1 ? powerRankings(week - 1) : null;
      if (power) power.forEach((r) => {
        const p = prev && prev.find((x) => x.id === r.id);
        r.move = p ? p.rank - r.rank : 0;
      });
      const luckSeason = power ? power.slice().sort((a, b) => b.luck - a.luck) : [];
      const winners = single.filter((s) => s.pts > s.oppPts), losers = single.filter((s) => s.pts < s.oppPts);
      const luckyWin = winners.slice().sort((a, b) => a.ap - b.ap)[0] || null;
      const unluckyLoss = losers.slice().sort((a, b) => b.ap - a.ap)[0] || null;
      const toughest = single.slice().sort((a, b) => b.oppPts - a.oppPts)[0] || null;

      /* ---- lineups ------------------------------------------------------ */
      const lrows = lw ? lw.rows.filter((r) => single.some((s) => s.id === r.teamId)) : [];
      const eff = (r) => (r.optimal ? r.actual / r.optimal : 1);
      const lineup = lrows.length ? {
        best: lrows.slice().sort((a, b) => eff(b) - eff(a))[0],
        worst: lrows.slice().sort((a, b) => b.left - a.left)[0],
        perfect: lrows.filter((r) => r.left < 0.005).map((r) => r.teamId),
        left: lrows.reduce((n, r) => n + r.left, 0),
        cost: lrows.filter((r) => r.costGame).map((r) => r.teamId),
        blunder: lrows.filter((r) => r.blunder && r.blunder.cost > 0).sort((a, b) => b.blunder.cost - a.blunder.cost)[0] || null,
        eff,
      } : null;

      /* ---- the front office ------------------------------------------- */
      const weekTx = ((txns || {})[SEASON] || []).filter((t) => t.status === "complete" && Number(t.leg) === week);
      const trades = weekTx.filter((t) => t.type === "trade").map((t) => {
        const ids = (t.roster_ids || []).map((r) => `r${r}`).filter((id) => teams[id]);
        return {
          teams: ids,
          sides: ids.map((id) => ({
            id,
            got: [
              ...Object.entries(t.adds || {}).filter(([, r]) => `r${r}` === id).map(([pid]) => pname(pid)),
              ...(t.draft_picks || []).filter((pk) => `r${pk.owner_id}` === id).map((pk) => `${pk.season} round ${pk.round} pick`),
              ...(t.waiver_budget || []).filter((x) => `r${x.receiver}` === id).map((x) => `$${x.amount} FAAB`),
            ],
          })),
        };
      });
      const adds = weekTx.filter((t) => t.type === "waiver" || t.type === "free_agent");
      const faab = S.waiverType === 2;
      const bids = adds.filter((t) => t.type === "waiver" && t.settings && t.settings.waiver_bid != null)
        .map((t) => ({ id: `r${Object.values(t.adds || {})[0]}`, pid: Object.keys(t.adds || {})[0], bid: Number(t.settings.waiver_bid) }))
        .filter((x) => teams[x.id] && x.pid).sort((a, b) => b.bid - a.bid);
      const busy = {};
      adds.forEach((t) => Object.values(t.adds || {}).forEach((r) => { busy[`r${r}`] = (busy[`r${r}`] || 0) + 1; }));
      const busiest = Object.entries(busy).filter(([id]) => teams[id]).sort((a, b) => b[1] - a[1])[0] || null;
      // The pickup who paid off this week: added this season, started, scored.
      const newcomers = wire ? wire.pickups.filter((p) => p.week <= week && (week - p.week) <= 4) : [];
      const wireHero = starters.filter((s) => newcomers.some((p) => p.pid === s.id && p.teamId === s.teamId)).sort((a, b) => b.pts - a.pts)[0] || null;

      /* ---- the playoff race --------------------------------------------- */
      let race = null;
      if (!playoff && HAS_PLAYOFFS) {
        const pic = buildPicture(week);
        const was = week > 1 ? buildPicture(week - 1) : null;
        const lastIn = pic.seeds[PLAYOFF_TEAMS - 1], firstOut = pic.seeds[PLAYOFF_TEAMS];
        const changes = [];
        TEAM_IDS.forEach((id) => {
          const f = pic.flags[id], o = was ? was.flags[id] : null;
          if (f === o) return;
          if (f === "z") changes.push({ id, what: BYES ? "clinched a first-round bye" : HAS_DIVISIONS ? "clinched the division" : "clinched the top seed" });
          else if (f === "x") changes.push({ id, what: "clinched a playoff spot" });
          else if (f === "e") changes.push({ id, what: "was eliminated from playoff contention" });
        });
        const sc = !FINISHED && week === lastPlayedWeek ? playoffScenarios(week) : null;
        race = {
          seeds: pic.seeds.slice(0, Math.min(pic.seeds.length, PLAYOFF_TEAMS + 2)).map((id, i) => ({ id, seed: i + 1, record: pic.stats[id].record, flag: pic.flags[id] || "", in: i < PLAYOFF_TEAMS })),
          bubble: lastIn && firstOut ? { lastIn, firstOut, gap: pic.stats[lastIn].score - pic.stats[firstOut].score } : null,
          changes,
          stakes: sc && sc.rows.length ? sc : null,
          weeksLeft: REGULAR_WEEKS - week,
        };
        race.changes.forEach((c) => notesFor.push({
          kind: `race-${c.id}`,
          pri: c.what.includes("eliminated") ? 48 : 58,
          title: c.what.includes("eliminated") ? `${plain(c.id)} are out` : `${plain(c.id)} ${c.what.replace("clinched", "clinch")}`,
          dek: c.what.includes("eliminated") ? `${plain(c.id)} can no longer reach the playoffs.` : `With ${plural(race.weeksLeft, "week")} of the regular season left.`,
        }));
      }

      /* ---- next week --------------------------------------------------- */
      let next = null;
      const nextWeek = week + 1;
      if (!playoff && nextWeek <= REGULAR_WEEKS && (schedule[nextWeek] || []).length) {
        const rank = (id) => (power ? (power.find((r) => r.id === id) || { rank: 99 }).rank : 99);
        const games2 = schedule[nextWeek].map(([a, b]) => ({ a, b, ra: rank(a), rb: rank(b), sa: statsAfter[a].record, sb: statsAfter[b].record }));
        const gotw = games2.slice().sort((x, y) => (x.ra + x.rb) - (y.ra + y.rb) || Math.abs(x.ra - x.rb) - Math.abs(y.ra - y.rb))[0];
        const sr = gotw ? series(oid(gotw.a), oid(gotw.b)) : null;
        next = { week: nextWeek, games: games2, gotw, series: sr };
      } else if (!playoff && nextWeek > REGULAR_WEEKS && HAS_PLAYOFFS) {
        next = { week: nextWeek, playoffs: true, games: [] };
      }

      /* ---- the headline ------------------------------------------------ */
      notesFor.sort((a, b) => b.pri - a.pri);
      const kinds = new Set();
      const heads = notesFor.filter((h) => { if (h.kind && kinds.has(h.kind)) return false; kinds.add(h.kind); return true; });
      let headline = heads[0] || null;
      if (!headline && byPts.length) {
        const t = byPts[0];
        headline = { title: `${plain(t.id)} lead the week with ${fmt(t.pts)}`, dek: `${t.pts > t.oppPts ? `${verbS(plain(t.id), "beat")}` : "Still lost to"} ${plain(t.opp)}, ${fmt(t.pts)}–${fmt(t.oppPts)}.` };
      }
      const alsoNotes = heads.slice(1, 4).map((n) => n.title);

      return {
        week, season: SEASON, league: model.name, playoff, hasBox: !!box,
        headline, also: alsoNotes,
        games: gameStories,
        numbers: {
          avg, median, total, high: byPts[0] || null, low: byPts[byPts.length - 1] || null,
          luckyWin, unluckyLoss, toughest,
          luckiest: luckSeason[0] || null, unluckiest: luckSeason[luckSeason.length - 1] || null,
        },
        power,
        players: {
          mvp: starters[0] || null,
          byPos,
          bench: bench[0] || null,
          dud: duds[0] && duds[0].pts < 5 ? duds[0] : null,
          wireHero,
        },
        lineup,
        moves: { trades, adds: adds.length, bids: faab ? bids.slice(0, 3) : [], busiest, faab, pname },
        race, next,
      };
    }


    /* ---- the recap as text, for a group chat ---------------------------- */
    function recapText(r) {
      const L = [`${r.league} · Week ${r.week} recap`];
      if (r.headline) L.push("", r.headline.title.toUpperCase(), r.headline.dek);
      r.also.forEach((t) => L.push(`• ${t}`));
      L.push("", "SCORES");
      r.games.forEach((g) => {
        L.push(`${g.label ? `${g.label}: ` : ""}${plain(g.w)} ${fmt(g.ws)} – ${fmt(g.ls)} ${plain(g.l)}`);
        if (g.notes.length) L.push(`   ${g.notes.join(". ")}.`);
      });
      if (r.power) {
        L.push("", "POWER RANKINGS");
        r.power.forEach((p) => L.push(`${p.rank}. ${plain(p.id)} (${p.record})${p.move ? ` ${p.move > 0 ? "▲" : "▼"}${Math.abs(p.move)}` : ""}`));
      }
      const n = r.numbers;
      L.push("", "BY THE NUMBERS");
      if (n.high) L.push(`High score: ${plain(n.high.id)}, ${fmt(n.high.pts)}`);
      L.push(`League average: ${fmt1(n.avg)}`);
      if (n.luckyWin && n.luckyWin.apOf) L.push(`Luckiest win: ${plain(n.luckyWin.id)}, ${fmt(n.luckyWin.pts)} (beats ${n.luckyWin.ap} of ${n.luckyWin.apOf})`);
      if (n.unluckyLoss && n.unluckyLoss.apOf) L.push(`Unluckiest loss: ${plain(n.unluckyLoss.id)}, ${fmt(n.unluckyLoss.pts)} (beats ${n.unluckyLoss.ap} of ${n.unluckyLoss.apOf})`);
      if (r.lineup) {
        L.push(`Best-set lineup: ${plain(r.lineup.best.teamId)} (${(100 * r.lineup.eff(r.lineup.best)).toFixed(1)}%)`);
        if (r.lineup.blunder) {
          const b = r.lineup.blunder.blunder;
          L.push(`Bench blunder: ${plain(r.lineup.blunder.teamId)} benched ${r.moves.pname(b.benched.pid)} (${fmt(b.benched.pts)})${r.lineup.blunder.costGame ? ", and it cost the game" : ""}`);
        }
      }
      if (r.players.mvp) {
        const P = r.players;
        L.push("", "PLAYERS OF THE WEEK", `MVP: ${P.mvp.name} ${fmt(P.mvp.pts)} (${plain(P.mvp.teamId)})`);
        if (P.wireHero) L.push(`Waiver-wire hero: ${P.wireHero.name} ${fmt(P.wireHero.pts)} (${plain(P.wireHero.teamId)})`);
        if (P.bench) L.push(`Best on a bench: ${P.bench.name} ${fmt(P.bench.pts)} (${plain(P.bench.teamId)})`);
      }
      if (r.moves.trades.length) {
        L.push("", "TRADES");
        r.moves.trades.forEach((t) => L.push(t.sides.map((s) => `${plain(s.id)} get ${s.got.join(", ") || "nothing"}`).join(" / ")));
      }
      if (r.race) {
        L.push("", "PLAYOFF RACE");
        r.race.seeds.forEach((s) => L.push(`${s.seed}. ${plain(s.id)} ${s.record}${s.flag ? ` (${s.flag})` : ""}${s.seed === PLAYOFF_TEAMS ? "\n   ---" : ""}`));
        r.race.changes.forEach((c) => L.push(`${plain(c.id)} ${c.what}.`));
      }
      if (r.next && r.next.gotw) L.push("", `NEXT WEEK'S GAME: ${plain(r.next.gotw.a)} (${r.next.gotw.sa}) vs ${plain(r.next.gotw.b)} (${r.next.gotw.sb})`);
      L.push("", location.href.split("#")[0]);
      return L.join("\n");
    }


    const PRIOR = (() => {
      const before = model.seasons.filter((s) => s.year < SEASON && s.playedWeeks.length).pop();
      if (!before) return null;
      const byOwner = {};
      Object.values(before.teams).forEach((t) => { byOwner[t.ownerId] = [t.wins, t.losses]; });
      const records = {};
      TEAM_IDS.forEach((id) => { if (byOwner[teams[id].ownerId]) records[id] = byOwner[teams[id].ownerId]; });
      return Object.keys(records).length ? { year: before.year, records } : null;
    })();

    function strengthOfSchedule() {
      const priorPct = (id) => {
        const [w, l] = PRIOR.records[id] || [0, 0];
        return w + l ? w / (w + l) : 0;
      };

      const opponents = {};
      TEAM_IDS.forEach((id) => { opponents[id] = []; });
      Object.keys(schedule).map(Number).filter((w) => w <= REGULAR_WEEKS).forEach((w) => {
        schedule[w].forEach(([a, b]) => { opponents[a].push(b); opponents[b].push(a); });
      });

      const rows = TEAM_IDS.map((id) => {
        const opps = opponents[id];
        const wins = opps.reduce((n, x) => n + (PRIOR.records[x] || [0, 0])[0], 0);
        const losses = opps.reduce((n, x) => n + (PRIOR.records[x] || [0, 0])[1], 0);
        const counts = opps.reduce((acc, x) => { acc[x] = (acc[x] || 0) + 1; return acc; }, {});
        const twice = Object.keys(counts)
          .filter((x) => counts[x] > 1)
          .sort((a, b) => priorPct(b) - priorPct(a));
        return { id, games: opps.length, wins, losses, twice, sos: wins + losses ? wins / (wins + losses) : 0 };
      });

      rows.sort((a, b) => b.sos - a.sos || teams[a.id].name.localeCompare(teams[b.id].name));
      const spread = Math.max(...rows.map((r) => Math.abs(r.sos - 0.5))) || 1;
      rows.forEach((r) => { r.deviation = r.sos - 0.5; r.magnitude = Math.abs(r.deviation) / spread; });
      return rows;
    }


    const HAS_BRACKET = season.postseason.some((g) => g.played);
    const SEASON_VIEWS = FINISHED
      ? [
        { id: "regular", label: "Regular Season", short: "Regular" },
        { id: "final", label: "Final Standings", short: "Final" },
        ...(HAS_BRACKET ? [{ id: "bracket", label: "Bracket" }] : [])
      ]
      : [
        { id: "panel-results", label: "Schedule" },
        { id: "panel-standings", label: "Standings" },
        ...(HAS_PLAYOFFS ? [{ id: "panel-picture", label: "Playoffs" }] : []),
        ...(PRIOR && Object.keys(schedule).length ? [{ id: "panel-sos", label: "Strength of Schedule", short: "SOS" }] : [])
      ];

    // A played week also has its recap (THE WEEK IN REVIEW).
    const RECAP_VIEW = { id: "panel-recap", label: "Recap" };
    const weekViews = (week) => [
      { id: "panel-results", label: isPlayed(week) || FINISHED ? "Results" : "Matchups" },
      { id: "panel-standings", label: "Standings" },
      ...(HAS_PLAYOFFS ? [{ id: "panel-picture", label: "Playoffs" }] : []),
      ...(isPlayed(week) ? [RECAP_VIEW] : [])
    ];

    const playoffViews = (week) => [
      { id: "panel-playoffs", label: "Bracket" },
      { id: "panel-standings", label: "Standings" },
      ...(gamesOfWeek(week).length ? [RECAP_VIEW] : [])
    ];

    const viewsFor = (week) => (week === 0 ? SEASON_VIEWS : week > REGULAR_WEEKS ? playoffViews(week) : weekViews(week));
    const HOME_VIEW = FINISHED ? "final" : SEASON_VIEWS[0].id;

    const state = FINISHED
      ? { week: 0, view: "final" }
      : { week: latestWeek, view: latestWeek > REGULAR_WEEKS ? "panel-playoffs" : latestWeek ? "panel-results" : SEASON_VIEWS[0].id };

    // Standings and the playoff picture for a week that has not been played
    // yet fall back to the most recent completed week.
    function asOfWeek(week) {
      const done = playedWeeks.filter((w) => w <= week);
      return done.length ? done[done.length - 1] : 0;
    }

    const isPlayed = (w) => playedWeeks.includes(w);


    const boxWeeks = () => model.boxWeeks(SEASON);
    const boxWeekCache = {};
    function boxWeek(week) {
      if (!boxWeekCache[week]) boxWeekCache[week] = model.boxWeek(SEASON, week).catch(() => null);
      return boxWeekCache[week];
    }

    const weeksText = (weeks) => (weeks.length > 1 ? `NFL Weeks ${weeks[0]}–${weeks[weeks.length - 1]}` : `NFL Week ${weeks[0]}`);

    return { SEASON, REGULAR_WEEKS, PLAYOFF_TEAMS, BYES, MEDIAN, HAS_PLAYOFFS, HAS_DIVISIONS, WB_ROUNDS, LB_ROUNDS, LAST_WEEK, DIVISION_NAMES, divisionOrder, latestWeek, lastPlayedWeek, CLINCH_KEY, TIE_RULE, PRIOR, HAS_BRACKET, SEASON_VIEWS, HOME_VIEW, state, computeStats, buildPicture, playoffScenarios, gamesBack, gamesLeft, gamesOfWeek, powerRankings, allPlay, weekRecap, recapText, strengthOfSchedule, viewsFor, asOfWeek, isPlayed, playoffWeekPlayed, lastPlayoffWeek, weeksText, boxWeek, postOf };
  };
})();
